# basic options
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll
show_downloads: false

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
